server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://120.77.222.189:3306/ysdb?&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .hmtl
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: ml.tanglei.ysdata.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

mode: LEGACYHTML5

